### ISSUE TITLE
(Ruby 2.3.1) report.rb:14:in `add_entry': wrong number of arguments (given 5, expected 6) (ArgumentError) 	from /lib/benchmark/ips/job.rb:345:in `create_report' 	

### ISSUE THREAD

**Issue by jasonfb** [davy/benchmark-bigo#14]
exception:
```
Calculating -------------------------------------
            #at 1000/Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-bigo-1.0.0/lib/benchmark/bigo/report.rb:14:in `add_entry': wrong number of arguments (given 5, expected 6) (ArgumentError)
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:345:in `create_report'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:283:in `block in run_benchmark'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:239:in `each'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:239:in `run_benchmark'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:193:in `block in run'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:192:in `times'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-ips-2.7.2/lib/benchmark/ips/job.rb:192:in `run'
	from /Users/jason/.rvm/gems/ruby-2.3.1/gems/benchmark-bigo-1.0.0/lib/benchmark/bigo.rb:37:in `bigo'
	from sample_benchmark_bigo.rb:3:in `<main>'
```

example in README crashes with 

Ruby 2.3.1

my code is basically only the README example, with the require at the top: https://gist.github.com/jasonfb/e8f9c42ef8cdf909aa65c320522ca511

crashes at end when run:

https://gist.github.com/jasonfb/d97514b7275dd13685666332a1d61303

**Comment by jasonfb** [comment]
the calling code appears to be coming from https://github.com/evanphx/benchmark-ips/blob/master/lib/benchmark/ips/job.rb#L346

**Comment by jasonfb** [comment]
fixed with https://github.com/davy/benchmark-bigo/pull/15
